### ISSUE TITLE
Cabinet sourcing

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#10]
Going to try to steal one from friends.

**Comment by acrymble** [comment]
No freebies, but Ben is trying to find a used one. Otherwise you can buy flatpack kits online for £150-£350ish.

**Comment by benosteen** [comment]
I've put a call out on the UK VAC www.ukvac.com/forum/default.asp which is full of enthusiasts. Already got one message about potential cabinets.

**Comment by acrymble** [comment]
Current status: we are not confident that we can get a good second hand option because they're all being refurbished and thus too expensive.

Thinking about a flat pack or a design job for a prop maker

**Comment by acrymble** [comment]
This has been ordered as flat pack.
