### ISSUE TITLE
Platform proof of principle for testing

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#17]
@benosteen can you try out the 'AdamsGame' on the pull request, and let me know if it works and more broadly how this might be improved. It's really basic at the moment, but demonstrates how the 'mario' game might work.

**Comment by benosteen** [comment]
I've moved it to an area where we can put prototypes. Simple unstyled list, but useful as a bookmark for the time being.

http://bl-labs.github.io/arcadeinterface/prototypes/

**Comment by acrymble** [comment]
How do I update that list?

**Comment by benosteen** [comment]
It just needs a small addition to the index.html page in the prototypes directory to add a game to the list of links. Nothing fancy!

**Comment by acrymble** [comment]
Thanks. Updated.
