### ISSUE TITLE
HTML/JS engine: http://phaser.io/?

### ISSUE THREAD

**Issue by benosteen** [BL-Labs/arcadeinterface#2]
I've had a look around at the options and this one seems to be the best (at least, is sensibly engineered from my perspective and takes a lot of work out of it).

http://phaser.io/ - lots of tutorials and documentation too.

**Comment by acrymble** [comment]
I'll read through that site, hopefully in the next week.

**Comment by acrymble** [comment]
I had no trouble getting this working. This seems like a fantastic option.
