### ISSUE TITLE
user testing games

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#21]
I need to try out the platformer on a couple of people to see how they react and if they get how to play.

**Comment by acrymble** [comment]
Also now have the swipe game.

**Comment by acrymble** [comment]
I did user testing on 4 history academics and 1 engineer.
2 had experience playing games (both under the age of 40), and 3 were adamant that they had never played a game in their life (two of whom were over 50).

---

Platformer:

The experience showed dramatically. On the platformer the experienced players knew instinctively how to play and collected the targets with ease. They knew to avoid the enemy, to bonk the block with their head, how to jump between platforms, and that they should collect the stars.

The inexperienced players died repeatedly at the first enemy, were unsure of themselves with the controls, struggled to do each task.

NO players noticed the textual instructions at the bottom of the screen telling them which door to choose.

One of the users suggested using speech bubbles for instruction, as you're naturally looking at the player so anything you need to notice (such as instructions) needs to be right next to where you're looking.

Another suggested a video at the beginning showing the player doing the types of things you want the person to do. Eg, jumping on enemies and collecting stars, etc.

All players said they had fun with the platformer and thought it was a worthwhile game.

---

Swipe Game

Again the experienced players 'got it' pretty quickly. They missed 2-3 falling images at the beginning before they got the hang of it. 3 of the players found it difficult to stop, even though the game only contained 1 image which appeared over and over again. They continued to classify the image correctly until I told them to stop. One player did so over 40 times. This has an addictive quality to it.

One of the experienced players struggled to understand the on-screen instructions.

**Comment by knavickas** [comment]
anon user tester

female, 35-45,

capability: COMPLETE BEGINNER, didn't have computer games as a child, RUBBISH hand-eye co-ordination.

suggestions:  platformer - make the main character larger and more obvious so it is clear who the user is controlling.

swiper - have some sort of count of how many faces recognised, with a star or similar 'earned' for say every 10 faces.

**Comment by acrymble** [comment]
Thanks to my ANONYMOUS tester for reminding me of her feedback :)
