### ISSUE TITLE
slot machine question

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#25]
@benosteen I've added a question about the slot machine game on the gameideas.md file.

**Comment by benosteen** [comment]
For each tag (portrait, heraldry, map), we should personally check a small batch of them. These are our golden set. The others that have been tagged by other people are our maybes. The third reel will have a mix of these, with the first two reels already 'held' on images from the golden set.

If a player stops the reel and does not choose to respin, they are asserting that the third reel matches the first two.

Edge cases: assertions when there are no respins left should be taken under caution!

The difficultly of the challenge is varied by changing the proportions of golden:maybe:random-untagged on the reel, always ensuring that there is at least one correct answer on it.

**Comment by benosteen** [comment]
(adding response to gameideas.md)

**Comment by acrymble** [comment]
This ties in with a wider need then to coordinate these various 'golden
sets', because I think we've now got the idea that each game should feed
into a master dataset that learns from previous contributions.

We should probably then prioritise getting the data, deciding on the
variables, and structuring that into a format that all the games can use
and feed into.
