### ISSUE TITLE
Backend logging service

### ISSUE THREAD

**Issue by benosteen** [BL-Labs/arcadeinterface#26]
Simple event-oriented key-value logging. For use with capturing state (someone is touching the controls) and for capturing crowdsourced information (img X is confirmed to have tag Y)

**Comment by acrymble** [comment]
Flask backend (http://flask.pocoo.org/).
JSON over HTTP.
Javascript does the calculating.
Stored as SQLite. SQL Alchemy.
JSON is the intermediary between JavaScript and Python.

Python runs the webserver, knows what images are on disk, knows what the tags are.

**Comment by acrymble** [comment]
Is there anything to report in terms of progress on this back end?
