### ISSUE TITLE
Doing a Mini Survey in Public Areas to Assess Demand for Games

### ISSUE THREAD

**Issue by mr-mahendra-mahey** [BL-Labs/arcadeinterface#28]
This would provide justification. We can find out how many people are actually playing games on their phones, as potential punters for the Arcade Machine.

Questionnaire would be very simple and we could get this out very soon, though would need to ensure it meets BL Policy guidelines. I can lead on this if you want.

Do you ever play games on your mobile device when at the BL?
If yes, for how long? When?

Would you play with a physical device?

Would you engage  in games that help the library make images more discoverable.

Male/Female
Age Range
Geographical Area
Subjects interested in
Must be anonymous, can be online, or paper based.

**Comment by acrymble** [comment]
I like it. If you can initiate that, that'd be amazing.

**Comment by benosteen** [comment]
Would be worth contacting the learning folk too - the school groups would give them a good angle on this.

**Comment by acrymble** [comment]
Related to this, even approaching people just standing around or otherwise
clearly waiting for time to pass would be worthwhile. Even if they don't
have their phone out.

Adam

**Comment by acrymble** [comment]
I think we're past this with the proposal.
