### ISSUE TITLE
Ethics at herts

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#29]
Hertfordshire wants me to submit an ethics application for this project because it involves human subjects. This will have to go in quickly.

**Comment by knavickas** [comment]
Let me know if you need some help with this, Adam, as I sit on the ethics committee and therefore can help you with the form. The main thing to stress on the form will be that all the participants will a) consent to taking part in your activities/games; b) that if children play them, they have the consent of their parents; c) that all data collected will be anonymised and kept securely.

Katrina

**Comment by acrymble** [comment]
Thanks Katrina. I spoke to Susan Grey and she now changes her mind. Trying
to sort out exactly what's needed, but I might be in touch.
