### ISSUE TITLE
Cool game we could repurpose (with permission)

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#31]
I think this could be quickly repurposed into a game we could use. Instead of repairing gears, you have to go to an image (at each of the awkward gear points) and a/b classify it - either destroy it with button A because it doesn't meet the game criteria (has a face) or collect it with button B:

http://jams.gamejolt.io/5minjam/games/the-clock-the-chaos/70751

I love the graphics too.

What do you think?

He is: https://twitter.com/MarcoEmiliozzi

**Comment by benosteen** [comment]
Seems great! I'll see about how we can mimic the structure when I'm back.
