### ISSUE TITLE
Game Jam in September

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#7]
put out a call out for a competition to get a series of games to put on the machine. Prize for the most used game? Hack weekend?

**Comment by acrymble** [comment]
Competitions have to go through legal, which takes ages. Best not to call it a competition. A thank you gift rather than a prize.

**Comment by acrymble** [comment]
Offer to let them enter the BL Awards competition with their entries.

**Comment by acrymble** [comment]
Need 3-4 weeks lead time. 2 day event. 20-30 tops. Hold in early September, and do it as a soft launch. Show them first, then get them to make more games. We have 3 games to show off they get to see the limits of the hardware and get excited.

**Comment by acrymble** [comment]
https://community.github.com/ Github sponsors events like this.
I suggest we ask them to sponsor Raspberry Pi's for the participants

**Comment by acrymble** [comment]
Draft budget, for 40 people (15 developers, 15 academics, 10 in house project team):
- Food (£12 p.p \* 2 days): £960
- Raspberry Pi for developers (£30 p.p. x 15): £450
- Keyboard controller board (£30 p.p x 15): £450
- Joysticks (£15 p.p x 15): £225
- 3 buttons (£3 p.p x 15): £45
- Misc expendables (£100)

TOTAL: £2,230

**Comment by acrymble** [comment]
Rethink on this event to follow a 'Ludum Dare' model, where we give game makers around the world a few challenges to create a social arcade game that helps collect metadata for historians. Possibly 3 videos of a historian pitching their challenge, describing their data and their needs, and then opening it to the floor.

Could do newspaper data, flickr photos, and maps.

Instead of an in-person event it's a disbursed call.

Adam to draft proposal.

**Comment by acrymble** [comment]
I've sent a draft proposal for the Game Jam to Ben and Mahendra for feedback. Need to think about funding for this pretty soon.

**Comment by acrymble** [comment]
Mahendra and Adam had a meeting to discuss the event today. We've decided on the following:

1) A Virtual Week, start of September, encouraging people to build a game for the week.
2) A day and a half long event on the Saturday (8am-8pm) / Sunday (11am-3pm) following. The event will take the following format:
    \* People must apply with at least a game concept, based on our loose set of rules. This ensures people have an idea they can develop on the day, as the event itself is short. A maximum of 15 people will be accepted.
     \* Attendees will get a mentoring session with an industry expert in the Saturday morning session. They will either get feedback on their idea, or on their prototype if they've been working during the Virtual week. Virtual participants can get feedback via Skype.
     \* They hack all day.
     \* They come back Sunday morning and present their results. Industry experts judge. Winners get an arcade kit.

We plan to seek funding for up to 3 travel bursaries for within the UK.

People:
    \* 15 participants
    \* 3 project team
    \* 4 industry experts

Budget:
    \* 22 people \* 4 meals = £880
    \* Judges expenses = £600
    \* 3 travel bursaries = £450
    \* 3 kits as prizes = £300

Total = £2,230

The goal was to create an event that meets the needs of the project, and of the participants. We believe this model gives participants benefits in the form of industry contacts, industry expert feedback, and possible prizes (the kits, plus the BL Labs award possibility).

**Comment by acrymble** [comment]
funding request sent to Hertfordshire.

**Comment by acrymble** [comment]
I have added draft text to a Google Drive doc and sent it to @benosteen and @mr-mahendra-mahey . Please edit this, as it has to look attractive for potential attendees. We're hoping to post this on Monday so we can start attracting people (particularly to the physical meetup).

**Comment by benosteen** [comment]
Looks good, we should probably link out to a few solid examples that help
define crowdsourcing to people at some point. I'm going to carry on making
the backend, so that we will have something that can be included in the
writeup.

Ben

**Comment by acrymble** [comment]
I've emailed itch.io to see if they're happy for us to use their site.

**Comment by acrymble** [comment]
itch.io is happy for us to use their service.

**Comment by acrymble** [comment]
http://itch.io/jam/676/edit

**Comment by acrymble** [comment]
Currently underway.

Blog post number 2 is live. Tweeting and awaiting results.
