### ISSUE TITLE
read up on metadata games

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#8]

**Comment by acrymble** [comment]
These games are missing the 'game' element, for the most part. They're after metadata, but havn't found a way to make it fun, or to move away from textual tagging as an activity. They feel like work. Some rely on 2 players, or even a second player elsewhere in the world logging on at the same time as you and hoping to play. Images are often difficult to see because it's clearly been designed for a phone but doesn't scale up for full screen computers.

**Comment by benosteen** [comment]
Agreed. There isn't a game element there aside from highscore chasing (weakly implemented at that). It's a shame as I know the head of the group is capable of making games, but it doesn't seem to filter down.
