### ISSUE TITLE
Set up framework on github

### ISSUE THREAD

**Issue by acrymble** [BL-Labs/arcadeinterface#9]
Try and get the framework hosted on github and runable from there. Otherwise, find other solution.

**Comment by benosteen** [comment]
By making a branch in the repository called "gh-pages", the branch is then visible at the following address:

http://bl-labs.github.io/arcadeinterface

Eg, I've added a basic shell for Phaser.io in a folder called 'game'. Does nothing but open a 800x800 black play area.

http://bl-labs.github.io/arcadeinterface/game/

**Comment by acrymble** [comment]
Ok I've tried to add in a proof of principle of a platform game I built. I've submitted a pull request but let me know if I've done anything wrong, because I'm still new to Git.

**Comment by acrymble** [comment]
This obviously works.
